mecoL1:
  et_dir: "./meco-features/"
  et_orig: "/Users/tzp466/Documents/research/data/meco/v1.2/"
  meco_webcam_dir: "./webcam_meco/"
  results_dir: "./results/"
  languages: ["en", "tr", "ru", "gr", "ge", "sp"]
  languages_web: ["de"] #"en", "de", "es", "tr", "ru", "gr"
